'use client'
import Link from 'next/link'
import { useEffect,useMemo,useState } from 'react'
import { useParams } from 'next/navigation'
import type { User } from '@supabase/supabase-js'
import { supabase } from '@/lib/supabase'

type Project={id:number;slug:string;title:string;description:string|null;role_slugs:string[];required_skill_slugs:string[];tasks:string[];success_criteria:string[];evidence_requirements:string[];estimated_hours:number;difficulty:number}
type Attempt={status:string;repo_url:string|null;demo_url:string|null;evidence_notes:string|null}

export default function ProjectDetail(){
 const params=useParams(); const slug=params.slug as string; const [user,setUser]=useState<User|null>(null); const [project,setProject]=useState<Project|null>(null); const [attempt,setAttempt]=useState<Attempt>({status:'not_started',repo_url:'',demo_url:'',evidence_notes:''}); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true)
 useEffect(()=>{const load=async()=>{const [{data:userData},{data:p,error}]=await Promise.all([supabase.auth.getUser(),supabase.from('practical_projects').select('*').eq('slug',slug).single()]); if(error||!p){setLoading(false);return} setUser(userData.user??null);setProject(p as Project); if(userData.user){const {data:a}=await supabase.from('user_projects').select('status,repo_url,demo_url,evidence_notes').eq('user_id',userData.user.id).eq('project_id',p.id).maybeSingle(); if(a)setAttempt(a as Attempt)} setLoading(false)};load()},[slug])
 const canComplete=useMemo(()=>Boolean(attempt.repo_url?.trim() && (attempt.evidence_notes?.trim().length??0)>=80),[attempt])
 const save=async(status=attempt.status)=>{if(!user||!project)return; if(status==='completed'&&!canComplete){setMessage('完了にはGitHub URLと80文字以上のEvidenceメモが必要です。');return} setSaving(true);setMessage(''); const now=new Date().toISOString(); const payload={user_id:user.id,project_id:project.id,status,repo_url:attempt.repo_url?.trim()||null,demo_url:attempt.demo_url?.trim()||null,evidence_notes:attempt.evidence_notes?.trim()||null,started_at:status==='not_started'?null:now,completed_at:status==='completed'?now:null,updated_at:now}; const {error}=await supabase.from('user_projects').upsert(payload); setSaving(false); if(error){setMessage(error.message);return} setAttempt(prev=>({...prev,status}));setMessage(status==='completed'?'成果物を完了として保存しました。':'進捗を保存しました。')}
 if(loading)return <main className="pageShell narrow"><p>Projectを読み込み中...</p></main>; if(!project)return <main className="pageShell narrow"><h1>Projectが見つかりません。</h1></main>; if(!user)return <main className="pageShell narrow"><div className="breadcrumb"><Link href="/projects">Projects</Link> / {project.title}</div><h1>{project.title}</h1><p>保存するにはログインしてください。</p><Link className="primaryLink" href="/login">ログイン</Link></main>
 return <main className="pageShell narrow"><div className="breadcrumb"><Link href="/">Engineer OS</Link> / <Link href="/career">Career OS</Link> / <Link href="/projects">Projects</Link> / {project.title}</div><span className="eyebrow">DIFFICULTY {project.difficulty} · 約{project.estimated_hours}時間</span><h1>{project.title}</h1><p className="leadText">{project.description}</p><div className="projectTags">{project.role_slugs.map(x=><span key={x}>{x}</span>)}</div>
 <section className="panel projectDetailSection"><h2>Build Tasks</h2><ol>{project.tasks.map((x,i)=><li key={i}>{x}</li>)}</ol></section>
 <section className="panel projectDetailSection"><h2>Success Criteria</h2><ul>{project.success_criteria.map((x,i)=><li key={i}>{x}</li>)}</ul></section>
 <section className="panel projectDetailSection"><h2>Evidence Required</h2><ul>{project.evidence_requirements.map((x,i)=><li key={i}>{x}</li>)}</ul></section>
 <section className="panel projectEvidence"><h2>Portfolio Evidence</h2><label>GitHub repository URL</label><input value={attempt.repo_url??''} onChange={e=>setAttempt(p=>({...p,repo_url:e.target.value}))} placeholder="https://github.com/..."/><label>Demo URL（任意）</label><input value={attempt.demo_url??''} onChange={e=>setAttempt(p=>({...p,demo_url:e.target.value}))} placeholder="https://..."/><label>Evidence / 振り返り（80文字以上）</label><textarea value={attempt.evidence_notes??''} onChange={e=>setAttempt(p=>({...p,evidence_notes:e.target.value}))} placeholder="何を設計し、どこで詰まり、何を根拠に判断し、次回どう改善するか..."/><small>{attempt.evidence_notes?.length??0} characters</small><div className="resultActions"><button className="secondaryButton" disabled={saving} onClick={()=>save('in_progress')}>途中保存</button><button className="primaryButton" disabled={saving||!canComplete} onClick={()=>save('completed')}>成果物を完了</button></div>{message&&<p className="statusMessage">{message}</p>}</section>
 </main>
}
