-- Engineer OS v0.9 — Tech Radar user decisions

create table if not exists public.user_tech_radar_decisions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_fingerprint text not null,
  source text not null,
  title text not null,
  url text,
  area text,
  decision text not null check (decision in ('candidate','watch','ignore')),
  note text,
  decided_at timestamptz not null default now(),
  unique (user_id, item_fingerprint)
);

alter table public.user_tech_radar_decisions enable row level security;

drop policy if exists "Users manage own tech radar decisions" on public.user_tech_radar_decisions;
create policy "Users manage own tech radar decisions"
on public.user_tech_radar_decisions
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

grant select, insert, update, delete on public.user_tech_radar_decisions to authenticated;
grant usage, select on all sequences in schema public to authenticated;
